version: "3.8"
services:
  server:
    build:
      context: .
      network: host
    ports:
      - 4000:4000
    environment:
      - SERVER_PORT=4000
      - CONNECTIONSTRING=mongodb://mongo:27017/careerCompassDBDev
    volumes:
      - ./:/app
    expose:
      - "4000"

    command: "npm run dev"

  mongo:
    image: mongo:4.4.5
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
