version: "3.8"
services:
  server:
    build:
      context: .
      network: host
    ports:
      - 4000:4000
    environment:
      - SERVER_PORT=4000
    volumes:
      - ./:/app
    expose:
      - "4000"
      - "8080"
    command: "npm start"
